name: Pylint

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    name: check ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-deps
        run: |
          python -m pip install --upgrade pip setuptools wheel black
          pip install -U -r requirements.txt

      - name: Run Pyright
        uses: jakebailey/pyright-action@v1
        with:
          version: '1.1.242'
          warnings: false
          no-comments: ${{ matrix.python-version != '3.x' }}
